server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
    sleuth:
      sampler:
        #采样率介于 0 - 1之间 1 则表示全部采样
        percentage: 1.0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
