server:
  port: 3344

spring:
  application:
    name: cloud-config-center  # 应用名称
  cloud:
    config:
      server:
        git:
          search-paths:
            - config
          uri: git@github.com:smart1026/cloud.git
          username: caijiaxing1992@163.com
          password: cjx19921219
      label: main

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka

