server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #使用druid数据源，替换C3P0
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    zookeeper:
      # 默认localhost:2181
      connect-string: localhost:2181




mybatis:  # model的包
  type-aliases-package: com.study.spring.entities
  mapper-locations: classpath:mapper/*.xml